" Vi互換をオフ
" if &compatible
  " set nocompatible
" endif

" 一旦ファイルタイプ関連を無効化する
" filetype off

" 256色指定
" set t_Co=256

" シンタックスハイライトの設定
" syntax enable

" ウィンドウサイズの設定
set columns=120
set lines=24

" ウィンドウ位置の指定
winpos 155 280

" フォントサイズの設定
" set guifont=MS_Mincho:h10
" set guifontwide=MS_Mincho:h10
" OS別
if has("mac")
  " mac用の設定
  set guifont=MS_Gothic:h10
  set guifontwide=MS_Gothic:h10
elseif has("unix")
  " unix固有の設定
  set guifont=Ricty\ Diminished\ 10
  set guifontwide=Ricty\ Diminished\ 10
elseif (has("win64") || has("win32unix") || ("win32"))
  " Windows(64bit, 32bit)+Cygwinの設定
  set guifont=MS_Gothic:h10
  set guifontwide=MS_Gothic:h10
endif


" カラースキームの設定
" colorscheme molokai


" 現在の行を強調表示
" set cursorline
"   " カレントウィンドウにのみ罫線を引く
"   augroup cch
"     autocmd! cch
"     autocmd WinLeave * set nocursorline
"     autocmd WinEnter,BufRead * set cursorline
"   augroup END
" hi clear CursorLine
" hi CursorLine gui=underline
" hi CursorLine cterm=underline,reverse ctermbg=darkgray


" 全角スペースをハイライト表示
" function! ZenkakuSpace()
"     highlight ZenkakuSpace cterm=reverse ctermfg=DarkMagenta gui=reverse guifg=DarkMagenta
" endfunction

" if has('syntax')
"     augroup ZenkakuSpace
"         autocmd!
"         autocmd ColorScheme       * call ZenkakuSpace()
"         autocmd VimEnter,WinEnter * match ZenkakuSpace /　/
"     augroup END
"     call ZenkakuSpace()
" endif


" .vimrc 最後の辺りに書く
" ファイルタイプ関連を有効にする
" filetype plugin indent on

